before_commands:
    - composer install

filter:
    excluded_paths: [vendor/*, app/*, web/*]

tools:
    php_cpd: true
    php_pdepend:
        excluded_dirs: [vendor]
    php_code_coverage: true
    php_hhvm: true
    php_mess_detector: true
    php_code_sniffer:
        enabled: true
        command: phpcs
        config:
            standard: PSR2
        filter:
            excluded_paths:
                - 'vendor/*'
