before_commands:
    - composer install

filter:
    excluded_paths: [vendor/*]

tools:
    php_cpd:
        enabled: true
        excluded_dirs: [vendor]
    php_pdepend:
        enabled: true
        excluded_dirs: [vendor]
    php_loc:
        enabled: true
        excluded_dirs: [vendor]
    php_code_coverage: true
    php_mess_detector: true
    php_code_sniffer:
        enabled: true
        command: phpcs
        config:
            standard: PSR2
        filter:
            excluded_paths:
                - 'vendor/*'
    php_analyzer: true
